project_name: mogura
env:
  - GO111MODULE=on
before:
  hooks:
    - go mod tidy
builds:
  - main: .
    binary: mogura
    ldflags:
      - -s -w
      - -X main.version={{.Version}}
      - -X main.revision={{.ShortCommit}}
    env:
      - CGO_ENABLED=0
    goos:
      - linux
      - darwin
      - windows
    goarch:
      - amd64
      - arm64
archives:
  - name_template: >-
      {{ .ProjectName }}_
      {{- .Os }}_
      {{- if eq .Arch "amd64" }}x86_64
      {{- else }}{{ .Arch }}{{ end }}
    format_overrides:
      - goos: windows
        format: zip
release:
  prerelease: auto

# https://goreleaser.com/customization/changelog/
# disabled auto create changelog from commit message.
changelog:
  skip: true

# homebrew
brews:
  - description: "ssh tunneling tool"
    repository:
      owner: reiki4040
      name: homebrew-tap
      token: "{{ .Env.GH_PAT }}"
    homepage: "https://github.com/reiki4040/mogura"
    install: |
      bin.install "mogura"
   # caveats: |
    #custom_block: # later use for devel version