# from https://github.com/linuxserver/docker-openssh-server
version: "3.9"
services:
  openssh-server:
    image: mogura-bastion:0.1.0
#    image: ghcr.io/linuxserver/openssh-server
    #container_name: openssh-server
    hostname: openssh-server #optional
    environment:
      PUID: 1000
      PGID: 1000
      TZ: "Tokyo/Japan"
      SUDO_ACCESS: true #optional
      PASSWORD_ACCESS: false #optional
      USER_NAME: "mogura" #optional
      PUBLIC_KEY: "ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIIa3Uf7s+t0E9cON+EMuQkNXhLNEDJobWr0ZKAzq0c85 root@85456cd13f85"
# PUBLIC_KEY does not quote "", if set then failed ssh.
#      PUBLIC_KEY_FILE=./test_rsa.pub #optiona
#      PUBLIC_KEY_DIR=/path/to/directory/containing/_only_/pubkeys #optional
#      USER_PASSWORD=password #optional
#      USER_PASSWORD_FILE=/path/to/file #optional
#    volumes:
#      - ./allow_forward_sshd_config:/config
    ports:
      - "2222:2222"
    restart: unless-stopped

  nginx:
    image: nginx:stable
    #container_name: nginx
    hostname: web-server
